# Generated by Django 6.0.5 on 2026-05-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('application_name', models.CharField(max_length=100)),
                ('application_no', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('application_date', models.DateField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
