# Generated by Django 6.0.5 on 2026-05-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_number',
            new_name='contact_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='application_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='aadhaar_no',
            field=models.CharField(default='000000000000', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=100)),
                ('application_no', models.CharField(max_length=50)),
                ('application_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_app.customer')),
            ],
        ),
    ]
