# Generated by Django 6.0.5 on 2026-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_rename_contact_number_customer_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('In Process', 'In Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='aadhaar_no',
            field=models.CharField(max_length=20),
        ),
    ]
