# Generated by Django 6.0.5 on 2026-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0003_application_remarks_alter_application_application_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhaar_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
