# Generated by Django 6.0.5 on 2026-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0004_alter_customer_aadhaar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
