# Generated by Django 6.0.5 on 2026-05-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0007_applicationstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
