# Generated by Django 6.0.5 on 2026-07-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0014_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
