# Generated by Django 6.0.5 on 2026-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0015_alter_application_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_reference_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
