# Generated by Django 6.0.5 on 2026-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0016_alter_application_payment_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
