# Generated by Django 6.0.5 on 2026-07-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0017_customer_is_registered_customer_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='registered_at',
        ),
    ]
