# Generated by Django 6.0.5 on 2026-10-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0018_remove_customer_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='customers_app.application'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='grievances/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='subject',
            field=models.CharField(default='General Grievance', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='customers_app.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='aadhaar_no',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='customers_app.customer'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Waiting for Customer', 'Waiting for Customer'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='grievancehistory',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customers_app.grievance'),
        ),
        migrations.CreateModel(
            name='GrievanceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='grievance_messages/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customers_app.grievance')),
            ],
        ),
    ]
